name: horoskope
description: Horoskope application
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fading_edge_scrollview: ^2.0.1
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  injectable: ^1.5.3
  intl: ^0.17.0
  recase: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  dart_code_metrics: ^4.13.0
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato/Lato-Regular.ttf
        - asset: fonts/Lato/Lato-Bold.ttf
          weight: 700
